// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idcngntaharsdjxaxpyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkY25nbnRhaGFyc2RqeGF4cHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDc4NzgsImV4cCI6MjA2MjUyMzg3OH0.MGzTWUfb_LOKVcURiGXmatL4TUydXFopagqKPbI1PEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);